In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=10000

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[3598, 644, 82, 9775], [3598, 644, 82, 2640], [3598, 2416, 82, 7302], [9049, 5723, 3090, 1412, 1805], [9049, 5723, 3090, 1412, 9032], [2757, 3598, 1401, 82, 7805], [7760, 1850, 2150, 1412]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3598  644   82 9775]
 [   0    0    0    0 3598  644   82 2640]
 [   0    0    0    0 3598 2416   82 7302]
 [   0    0    0 9049 5723 3090 1412 1805]
 [   0    0    0 9049 5723 3090 1412 9032]
 [   0    0    0 2757 3598 1401   82 7805]
 [   0    0    0    0 7760 1850 2150 1412]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.04803648  0.04281307  0.00561316  0.04751441 -0.01646291
   -0.04244141  0.04513487  0.01544911  0.02534476 -0.03449025]
  [-0.04803648  0.04281307  0.00561316  0.04751441 -0.01646291
   -0.04244141  0.04513487  0.01544911  0.02534476 -0.03449025]
  [-0.04803648  0.04281307  0.00561316  0.04751441 -0.01646291
   -0.04244141  0.04513487  0.01544911  0.02534476 -0.03449025]
  [-0.04803648  0.04281307  0.00561316  0.04751441 -0.01646291
   -0.04244141  0.04513487  0.01544911  0.02534476 -0.03449025]
  [-0.0239544   0.02106503  0.006389    0.00710522 -0.00737267
    0.03627416 -0.01375905  0.03965523  0.02717997  0.03583902]
  [-0.00064318 -0.03472818 -0.04874406  0.00812228 -0.03832481
    0.03960352 -0.00660658  0.01657816 -0.01899123 -0.03462071]
  [ 0.0071651   0.02729466  0.01651779 -0.0271476   0.01955697
    0.04129085 -0.04923526 -0.01658828  0.00691857 -0.02065674]
  [-0.03771895 -0.02032013 -0.01451648  0.03694149  0.02236904
    0.0388946  -0.03374664  0.02978854 -0.045744

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3598,  644,   82, 9775])

In [15]:
print(model.predict(embedded_docs)[0])

[[-0.04803648  0.04281307  0.00561316  0.04751441 -0.01646291 -0.04244141
   0.04513487  0.01544911  0.02534476 -0.03449025]
 [-0.04803648  0.04281307  0.00561316  0.04751441 -0.01646291 -0.04244141
   0.04513487  0.01544911  0.02534476 -0.03449025]
 [-0.04803648  0.04281307  0.00561316  0.04751441 -0.01646291 -0.04244141
   0.04513487  0.01544911  0.02534476 -0.03449025]
 [-0.04803648  0.04281307  0.00561316  0.04751441 -0.01646291 -0.04244141
   0.04513487  0.01544911  0.02534476 -0.03449025]
 [-0.0239544   0.02106503  0.006389    0.00710522 -0.00737267  0.03627416
  -0.01375905  0.03965523  0.02717997  0.03583902]
 [-0.00064318 -0.03472818 -0.04874406  0.00812228 -0.03832481  0.03960352
  -0.00660658  0.01657816 -0.01899123 -0.03462071]
 [ 0.0071651   0.02729466  0.01651779 -0.0271476   0.01955697  0.04129085
  -0.04923526 -0.01658828  0.00691857 -0.02065674]
 [-0.03771895 -0.02032013 -0.01451648  0.03694149  0.02236904  0.0388946
  -0.03374664  0.02978854 -0.04574422  0.02321241]]
